; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x296 y25 w113 h176, Üldine
Gui Add, CheckBox, vChkKaalukaotus gChkKaalukaotusClicked x304 y40 w77 h17, kaalukaotus
Gui Add, CheckBox, vChkIsutus gChkIsutusClicked x304 y57 w51 h23, isutus
Gui Add, CheckBox, vChkPalavik gChkPalavikClicked x304 y79 w54 h23, palavik
Gui Add, CheckBox, vChkKulmavarinad gChkKulmavarinadClicked x304 y102 w85 h23, külmavärinad
Gui Add, CheckBox, vChkMinestustunne gChkMinestustunneClicked x304 y125 w87 h23, minestustunne
Gui Add, GroupBox, x296 y202 w113 h132, Silmad
Gui Add, CheckBox, vChkPrillid gChkPrillidClicked x304 y217 w46 h23, prillid
Gui Add, CheckBox, vChkTopeltnagemine gChkTopeltnagemineClicked x304 y239 w91 h23, topeltnägemine
Gui Add, CheckBox, vChkValguskartus gChkValguskartusClicked x304 y262 w81 h23, valguskartus
Gui Add, GroupBox, x296 y335 w113 h154, KNK
Gui Add, GroupBox, x416 y26 w112 h134, Kardiovaskulaar
Gui Add, GroupBox, x416 y162 w113 h176, GI
Gui Add, GroupBox, x416 y338 w113 h130, GU
Gui Add, GroupBox, x416 y467 w113 h130, MSK
Gui Add, GroupBox, x536 y25 w113 h153, Nahk
Gui Add, GroupBox, x535 y178 w114 h153, Neuro
Gui Add, GroupBox, x536 y333 w113 h154, Psühh
Gui Add, GroupBox, x656 y25 w114 h153, Endokriinne
Gui Add, GroupBox, x656 y181 w113 h136, Hemato/lümf
Gui Add, CheckBox, vChkNohu gChkNohuClicked x304 y350 w51 h23, nohu
Gui Add, CheckBox, vChkKurguvalu gChkKurguvaluClicked x304 y373 w67 h23, kurguvalu
Gui Add, CheckBox, vChkHambad gChkHambadClicked x304 y396 w66 h23, hambad
Gui Add, CheckBox, vChkKuulmisprobleeme gChkKuulmisprobleemeClicked x304 y419 w103 h23, kuulmisprobleeme
Gui Add, CheckBox, vChkKVValu gChkKVValuClicked x423 y40 w45 h23, valu
Gui Add, CheckBox, vChkPuperdused gChkPuperdusedClicked x423 y63 w78 h28, puperdused
Gui Add, CheckBox, vChkTursed gChkTursedClicked x423 y91 w51 h23, tursed
Gui Add, CheckBox, vChkIiveldus gChkIiveldusClicked x424 y173 w59 h27, iiveldus
Gui Add, CheckBox, vChkOksendamine gChkOksendamineClicked x424 y198 w85 h23, oksendamine
Gui Add, CheckBox, vChkRoeMuutunud gChkRoeMuutunudClicked x424 y268 w85 h23, roe muutunud
Gui Add, CheckBox, vChkKorvetised gChkKorvetisedClicked x424 y221 w69 h23, kõrvetised
Gui Add, Edit, hWndhEdtValue vEdtKohutegevus gEdtKohutegevusChanged x424 y246 w97 h21
SendMessage 0x1501, 1, "kõhutegevus",, ahk_id %hEdtValue% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkDusuuria gChkDusuuriaClicked x424 y353 w61 h23, düsuuria
Gui Add, CheckBox, vChkHematuuria gChkHematuuriaClicked x424 y376 w73 h23, hematuuria
Gui Add, CheckBox, vChkSagenenud gChkSagenenudClicked x424 y399 w73 h23, sagenenud
Gui Add, Edit, hWndhEdtValue2 vEdtUldineMuu gEdtUldineMuuChanged x304 y152 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue2% ; EM_SETCUEBANNER
Gui Add, Edit, hWndhEdtValue3 vEdtSilmadMuu gEdtSilmadMuuChanged x304 y286 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue3% ; EM_SETCUEBANNER
Gui Add, Edit, hWndhEdtValue4 vEdtKNKMuu gEdtKNKMuuChanged x304 y442 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue4% ; EM_SETCUEBANNER
Gui Add, Edit, hWndhEdtValue5 vEdtKVMuu gEdtKVMuuChanged x422 y114 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue5% ; EM_SETCUEBANNER
Gui Add, Edit, hWndhEdtValue6 vEdtGUMuu gEdtGUMuuChanged x424 y422 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue6% ; EM_SETCUEBANNER
Gui Add, Edit, hWndhEdtValue7 vEdtGIMuu gEdtGIMuuChanged x424 y292 w98 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue7% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkMualgia gChkMualgiaClicked x424 y482 w58 h23, müalgia
Gui Add, CheckBox, vChkArtralgia gChkArtralgiaClicked x424 y505 w58 h23, artralgia
Gui Add, CheckBox, vChkKangus gChkKangusClicked x424 y528 w55 h23, kangus
Gui Add, Edit, hWndhEdtValue8 vEdtMSKMuu gEdtMSKMuuChanged x424 y551 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue8% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkLoove gChkLooveClicked x544 y40 w45 h22, lööve
Gui Add, CheckBox, vChkHaavu gChkHaavuClicked x544 y62 w68 h23, haav(and)
Gui Add, CheckBox, vChkDiskoloratsioon gChkDiskoloratsioonClicked x544 y85 w90 h23, diskoloratsioon
Gui Add, CheckBox, vChkSugelus gChkSugelusClicked x544 y108 w55 h23, sügelus
Gui Add, Edit, hWndhEdtValue9 vEdtNahkMuu gEdtNahkMuuChanged x544 y131 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue9% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkPeavalu gChkPeavaluClicked x543 y193 w59 h23, peavalu
Gui Add, CheckBox, vChkPearinglus gChkPearinglusClicked x543 y216 w69 h23, pearinglus
Gui Add, CheckBox, vChkParees gChkPareesClicked x543 y239 w92 h23, parees/pleegia
Gui Add, CheckBox, vChkDusesteesia gChkDusesteesiaClicked x543 y262 w79 h23, düsesteesia
Gui Add, Edit, hWndhEdtValue10 vEdtNeuroMuu gEdtNeuroMuuChanged x543 y285 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue10% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkDepressioon gChkDepressioonClicked x544 y348 w80 h23, depressioon
Gui Add, CheckBox, vChkLuulud gChkLuuludClicked x544 y371 w48 h23, luulud
Gui Add, CheckBox, vChkUnehaired gChkUnehairedClicked x544 y394 w68 h23, unehäired
Gui Add, CheckBox, vChkMaluhaired gChkMaluhairedClicked x544 y417 w71 h23, mäluhäired
Gui Add, Edit, hWndhEdtValue11 vEdtPsuhhMuu gEdtPsuhhMuuChanged x544 y440 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue11% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkPoluuuria gChkPoluuuriaClicked x664 y40 w67 h23, polüuuria
Gui Add, CheckBox, vChkPoludipsia gChkPoludipsiaClicked x664 y63 w70 h23, polüdipsia
Gui Add, CheckBox, vChkKulmatalumatus gChkKulmatalumatusClicked x664 y86 w94 h23, külmatalumatus
Gui Add, CheckBox, vChkKuumatalumatus gChkKuumatalumatusClicked x664 y109 w97 h23, kuumatalumatus
Gui Add, Edit, hWndhEdtValue12 vEdtEndoMuu gEdtEndoMuuChanged x664 y132 w98 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue12% ; EM_SETCUEBANNER
Gui Add, CheckBox, vChkSinikad gChkSinikadClicked x663 y196 w98 h28, kerge sinikate teke
Gui Add, CheckBox, vChkVeritsemine gChkVeritsemineClicked x663 y224 w96 h24, sage ja pikk veritsemine
Gui Add, CheckBox, vChkLumfadenopaatia gChkLumfadenopaatiaClicked x663 y248 w98 h23, lümfadenopaatia
Gui Add, Edit, hWndhEdtValue13 vEdtHematoMuu gEdtHematoMuuChanged x663 y271 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue13% ; EM_SETCUEBANNER
Gui Add, GroupBox, x656 y319 w113 h115, Allergia/immuun
Gui Add, CheckBox, vChkSageInf gChkSageInfClicked x664 y335 w84 h28, sagedased infektsioonid
Gui Add, CheckBox, vChkRiniit gChkRiniitClicked x664 y363 w85 h23, allergiline riniit
Gui Add, Edit, hWndhEdtValue14 vEdtAllergiaMuu gEdtAllergiaMuuChanged x664 y387 w97 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue14% ; EM_SETCUEBANNER
Gui Add, GroupBox, x792 y9 w128 h387, Sotsiaalne anamnees
Gui Add, CheckBox, vChkSuitsetaja gChkSuitsetajaClicked x799 y46 w65 h23, suitsetaja
Gui Add, CheckBox, vChkSuitsetanud gChkSuitsetanudClicked x799 y69 w78 h30, varasemalt suitsetanud
Gui Add, CheckBox, vChkAlko gChkAlkoClicked x799 y99 w56 h23, alkohol
Gui Add, CheckBox, vChkNarko gChkNarkoClicked x799 y122 w89 h23, narkootikumid
Gui Add, Text, x799 y23 w120 h23 +0x200  , Kahjulikud harjumused:
Gui Add, Text, x799 y145 w120 h23 +0x200  , Funktsionaalne seisund:
Gui Add, CheckBox, vChkFnKepp gChkFnKeppClicked x799 y168 w46 h23, kepp
Gui Add, CheckBox, vChkFnRulaator gChkFnRulaatorClicked x799 y191 w56 h23, rulaator
Gui Add, CheckBox, vChkFnVoodihaige gChkFnVoodihaigeClicked x799 y214 w76 h23, voodihaige
Gui Add, Edit, hWndhEdtValue15 vEdtFnMuu gEdtFnMuuChanged x799 y237 w113 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue15% ; EM_SETCUEBANNER
Gui Add, Text, x799 y259 w46 h23 +0x200  , Elukoht:
Gui Add, Edit, hWndhEdtValue16 vEdtElukohtMuu gEdtElukohtMuuChanged x799 y327 w113 h21
SendMessage 0x1501, 1, "linn",, ahk_id %hEdtValue16% ; EM_SETCUEBANNER
Gui Add, Text, x799 y348 w33 h23 +0x200  , Amet:
Gui Add, Edit, vEdtAmet gEdtAmetChanged x799 y371 w113 h21
Gui Add, GroupBox, x928 y9 w120 h112, Pereanamnees:
Gui Add, GroupBox, x928 y126 w120 h193, Keskkond
Gui Add, Text, x936 y142 w105 h33, Kokkupuude kemikaalidega:
Gui Add, Edit, vEdtKemikaalid gEdtKemikaalidChanged x936 y177 w105 h21
Gui Add, Text, x936 y198 w72 h23 +0x200 , Koduloomad:
Gui Add, Edit, vEdtKoduloomad gEdtKoduloomadChanged x936 y221 w105 h21
Gui Add, Text, x936 y242 w58 h23 +0x200 , Reisimised:
Gui Add, Edit, hWndhEdtValue20 vEdtKeskkondMuu gEdtKeskkondMuuChanged x936 y290 w105 h21
SendMessage 0x1501, 1, "muu",, ahk_id %hEdtValue20% ; EM_SETCUEBANNER
Gui Add, Edit, vEdtReisimised gEdtReisimisedChanged x936 y265 w105 h21
Gui Add, Edit, vEdtPereanamnees gEdtPereanamneesChanged x936 y47 w105 h66 +Multi
Gui Add, GroupBox, x8 y387 w264 h53, Operatsioonid
Gui Add, Edit, vEdtOperatsioonid gEdtOperatsioonidChanged x16 y402 w249 h31 +Multi
Gui Add, GroupBox, x9 y441 w136 h144, Ravimid
Gui Add, Edit, vEdtRavimid gEdtRavimidChanged x16 y456 w122 h121
Gui Add, GroupBox, x152 y442 w121 h64, Allergiad
Gui Add, Edit, vEdtAllergiad gEdtAllergiadChanged x160 y456 w105 h42 +Multi
Gui Add, GroupBox, x153 y515 w120 h71, Vaktsineerimised
Gui Add, Edit, vEdtVaktsineerimised gEdtVaktsineerimisedChanged x159 y554 w105 h24
Gui Add, CheckBox, vChkPensionar gChkPensionarClicked x846 y348 w66 h23, pensionär
Gui Add, CheckBox, vChkElumaja gChkElumajaClicked x799 y282 w59 h23, eramaja
Gui Add, CheckBox, vChkKortermaja gChkKortermajaClicked x799 y304 w120 h23, kortermaja
Gui Add, GroupBox, x287 y9 w489 h592, Organsüsteemide läbivaatus
Gui Add, GroupBox, x7 y10 w266 h232, Haiguse anamnees
Gui Add, Text, x16 y25 w120 h23 +0x200, Haiglasse pöördumine:
Gui Add, CheckBox, vChkTuliIse gChkTuliIseClicked x16 y48 w50 h23, tuli ise
Gui Add, CheckBox, vChkPaSaatekirjaga gChkPaSaatekirjagaClicked x16 y71 w93 h23, PA saatekirjaga
Gui Add, CheckBox, vChkKAga gChkKAgaClicked x66 y48 w55 h23, KA-ga
Gui Add, Edit, hWndhEdtValue27 vEdtMuuPoordumine gEdtMuuPoordumineChanged x16 y95 w120 h21
SendMessage 0x1501, 1, "muu pöördumine",, ahk_id %hEdtValue27% ; EM_SETCUEBANNER
Gui Add, Edit, vEdtPohikaebus gEdtPohikaebusChanged x144 y48 w120 h67 +Multi
Gui Add, Text, x144 y25 w120 h23 +0x200, Põhikaebus:
Gui Add, Text, x16 y120 w105 h23 +0x200, Täiendav anamnees:
Gui Add, Edit, vEdtTaiendavAnamnees gEdtTaiendavAnamneesChanged x16 y144 w248 h89 +Multi
Gui Add, GroupBox, x7 y248 w266 h137, Kaasuvad haigused
Gui Add, CheckBox, vChkKaasuvHTN gChkKaasuvHTNClicked x16 y263 w87 h23, hüpertensioon
Gui Add, CheckBox, vChkKaasuvFA gChkKaasuvFAClicked x103 y263 w34 h23, FA
Gui Add, CheckBox, vChkKaasuvKolesteroleemia gChkKaasuvKolesteroleemiaClicked x137 y264 w120 h23, hüperkolesteroleemia
Gui Add, CheckBox, vChkKaasuvHupotureoos gChkKaasuvHupotureoosClicked x16 y285 w80 h23, hüpotüreoos
Gui Add, Edit, vEdtKaasuvad gEdtKaasuvadChanged x16 y308 w248 h68 +Multi
Gui Add, CheckBox, vChkVaktsGripp gChkVaktsGrippClicked x160 y530 w44 h23, gripp
Gui Add, CheckBox, vChkAbielus gChkAbielusClicked x936 y24 w58 h23, abielus
Gui Add, CheckBox, vChkLapsi gChkLapsiClicked x994 y23 w42 h23, laps
Gui Add, CheckBox, vChkUldineNorm gChkUldineNormClicked x304 y173 w63 h23, normileid
Gui Add, CheckBox, vChkSilmadNorm gChkSilmadNormClicked x304 y307 w63 h23, normileid
Gui Add, CheckBox, vChkKNKNorm gChkKNKNormClicked x304 y464 w63 h23, normileid
Gui Add, CheckBox, vChkKVNorm gChkKVNormClicked x424 y135 w63 h23, normileid
Gui Add, CheckBox, vChkGINorm gChkGINormClicked x424 y313 w63 h23, normileid
Gui Add, CheckBox, vChkGUNorm gChkGUNormClicked x424 y443 w63 h23, normileid
Gui Add, CheckBox, vChkMSKNorm gChkMSKNormClicked x424 y572 w63 h23, normileid
Gui Add, CheckBox, vChkNahkNorm gChkNahkNormClicked x544 y152 w63 h23, normileid
Gui Add, CheckBox, vChkNeuroNorm gChkNeuroNormClicked x544 y306 w63 h23, normileid
Gui Add, CheckBox, vChkPsuhhNorm gChkPsuhhNormClicked x544 y461 w63 h23, normileid
Gui Add, CheckBox, vChkEndoNorm gChkEndoNormClicked x664 y153 w63 h23, normileid
Gui Add, CheckBox, vChkHematoNorm gChkHematoNormClicked x664 y292 w63 h23, normileid
Gui Add, CheckBox, vChkAllergiaNorm gChkAllergiaNormClicked x661 y408 w63 h23, normileid
Gui Add, Edit, vEdtEelvaade x16 y622 w1025 h228 +ReadOnly +Multi
Gui Add, GroupBox, x8 y602 w1041 h254, Anamneesi eelvaade

Gui Show, w1054 h862, Anamnees
Return

ChkKaalukaotusClicked:
Return

ChkIsutusClicked:
Return

ChkPalavikClicked:
Return

ChkKulmavarinadClicked:
Return

ChkMinestustunneClicked:
Return

ChkPrillidClicked:
Return

ChkTopeltnagemineClicked:
Return

ChkValguskartusClicked:
Return

ChkNohuClicked:
Return

ChkKurguvaluClicked:
Return

ChkHambadClicked:
Return

ChkKuulmisprobleemeClicked:
Return

ChkKVValuClicked:
Return

ChkPuperdusedClicked:
Return

ChkTursedClicked:
Return

ChkIiveldusClicked:
Return

ChkOksendamineClicked:
Return

ChkRoeMuutunudClicked:
Return

ChkKorvetisedClicked:
Return

EdtKohutegevusChanged:
Return

ChkDusuuriaClicked:
Return

ChkHematuuriaClicked:
Return

ChkSagenenudClicked:
Return

EdtUldineMuuChanged:
Return

EdtSilmadMuuChanged:
Return

EdtKNKMuuChanged:
Return

EdtKVMuuChanged:
Return

EdtGUMuuChanged:
Return

EdtGIMuuChanged:
Return

ChkMualgiaClicked:
Return

ChkArtralgiaClicked:
Return

ChkKangusClicked:
Return

EdtMSKMuuChanged:
Return

ChkLooveClicked:
Return

ChkHaavuClicked:
Return

ChkDiskoloratsioonClicked:
Return

ChkSugelusClicked:
Return

EdtNahkMuuChanged:
Return

ChkPeavaluClicked:
Return

ChkPearinglusClicked:
Return

ChkPareesClicked:
Return

ChkDusesteesiaClicked:
Return

EdtNeuroMuuChanged:
Return

ChkDepressioonClicked:
Return

ChkLuuludClicked:
Return

ChkUnehairedClicked:
Return

ChkMaluhairedClicked:
Return

EdtPsuhhMuuChanged:
Return

ChkPoluuuriaClicked:
Return

ChkPoludipsiaClicked:
Return

ChkKulmatalumatusClicked:
Return

ChkKuumatalumatusClicked:
Return

EdtEndoMuuChanged:
Return

ChkSinikadClicked:
Return

ChkVeritsemineClicked:
Return

ChkLumfadenopaatiaClicked:
Return

EdtHematoMuuChanged:
Return

ChkSageInfClicked:
Return

ChkRiniitClicked:
Return

EdtAllergiaMuuChanged:
Return

ChkSuitsetajaClicked:
Return

ChkSuitsetanudClicked:
Return

ChkAlkoClicked:
Return

ChkNarkoClicked:
Return

ChkFnKeppClicked:
Return

ChkFnRulaatorClicked:
Return

ChkFnVoodihaigeClicked:
Return

EdtFnMuuChanged:
Return

EdtElukohtMuuChanged:
Return

EdtAmetChanged:
Return

EdtKemikaalidChanged:
Return

EdtKoduloomadChanged:
Return

EdtKeskkondMuuChanged:
Return

EdtReisimisedChanged:
Return

EdtPereanamneesChanged:
Return

EdtOperatsioonidChanged:
Return

EdtRavimidChanged:
Return

EdtAllergiadChanged:
Return

EdtVaktsineerimisedChanged:
Return

ChkPensionarClicked:
Return

ChkElumajaClicked:
Return

ChkKortermajaClicked:
Return

ChkTuliIseClicked:
Return

ChkPaSaatekirjagaClicked:
Return

ChkKAgaClicked:
Return

EdtMuuPoordumineChanged:
Return

EdtPohikaebusChanged:
Return

EdtTaiendavAnamneesChanged:
Return

ChkKaasuvHTNClicked:
Return

ChkKaasuvFAClicked:
Return

ChkKaasuvKolesteroleemiaClicked:
Return

ChkKaasuvHupotureoosClicked:
Return

EdtKaasuvadChanged:
Return

ChkVaktsGrippClicked:
Return

ChkAbielusClicked:
Return

ChkLapsiClicked:
Return

ChkUldineNormClicked:
Return

ChkSilmadNormClicked:
Return

ChkKNKNormClicked:
Return

ChkKVNormClicked:
Return

ChkGINormClicked:
Return

ChkGUNormClicked:
Return

ChkMSKNormClicked:
Return

ChkNahkNormClicked:
Return

ChkNeuroNormClicked:
Return

ChkPsuhhNormClicked:
Return

ChkEndoNormClicked:
Return

ChkHematoNormClicked:
Return

ChkAllergiaNormClicked:
Return

GuiEscape:
GuiClose:
    ExitApp
